# Generated by Django 4.2.4 on 2023-08-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('from_email', models.EmailField(max_length=40)),
                ('message', models.TextField()),
            ],
        ),
    ]
